// export const ADD_TODO = "ADD_TODO"
// export const TOGGLE_TODO = "TOGGLE_TODO"
// export const REMOVE_TODO = "REMOVE_TODO"
// export const MARK_COMPLETED = "MARK_COMPLETED"
// export const MARK_INCOMPLETE = "MARK_INCOMPLETE"
// export const FILTER_TODO = "FILTER_TODO"
// export const EDIT_TODO = "EDIT_TODO"
// export const SET_TASKS = "SET_TASKS"

export const TaskActionTypes = {
  FETCH_TASKS_REQUEST: "FETCH_TASKS_REQUEST",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILURE: "FETCH_TASKS_FAILURE",

  ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_FAILURE: "ADD_TASK_FAILURE",

  UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",

  SET_FILTER: "SET_FILTER",

  TOGGLE_TASK_COMPLETION_REQUEST: "TOGGLE_TASK_COMPLETION_REQUEST",
  TOGGLE_TASK_COMPLETION_SUCCESS: "TOGGLE_TASK_COMPLETION_SUCCESS",
  TOGGLE_TASK_COMPLETION_FAILURE: "TOGGLE_TASK_COMPLETION_FAILURE",
};
